name: Telegram Release Notifications

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: get_date
        run: echo "current_date=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Process release notes
        id: process_release_notes
        run: |
          # Обработка описания релиза:
          # Первая строка остаётся без изменений, все последующие непустые строки получают префикс "• "
          RELEASE_BODY=$(echo "${{ github.event.release.body }}" | awk 'NR==1 { print } NR>1 { if($0 ~ /./) { print "• " $0 } else { print } }')
          echo "release_body<<EOF" >> $GITHUB_ENV
          echo "${RELEASE_BODY}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Get repository name
        id: get_repo_name
        run: echo "repo_name=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: "-1002348215825"   # ID вашего канала или чата
          token: "8196735240:AAHJ7VyISGE3eiwBxu74VlUMif7JPyX5OHY"
          format: HTML
          message: |
            📌 <b>Новый релиз в проекте:</b> ${{ env.repo_name }}
            🏷️ <b>Название релиза:</b> ${{ github.event.release.name }} (<i>${{ github.event.release.tag_name }}</i>)
            🗓️ <b>Дата:</b> ${{ env.current_date }}
            ✏️ <b>Описание:</b>
            ${{ env.release_body }}
